export const FETCH_CAPS_REQUEST = "FETCH_CAPS_REQUEST";
export const FETCH_CAPS_FAILURE = "FETCH_CAPS_FAILURE";
export const FETCH_CAPS_FINALLY = "FETCH_CAPS_FINALLY";
export const FETCH_CAPS_SUCCESS = "FETCH_CAPS_SUCCESS";
export const CAPS_SEARCH = "CAPS_SEARCH";
